(function() {
	app.directive('dhxMenu', function() {
		return {
			restrict: 'A',
			link: function ($scope, element, attrs) {
				var myMenu;
				myMenu = new dhtmlXMenuObject("menuObj");
				myMenu.setIconset("awesome");
				// initing
				myMenu.addNewSibling(null, "file", "File", false);
					myMenu.addNewChild("file", 0, "newProject", "New Project", false, "fa fa-plus");
					myMenu.addNewChild("file", 1, "delProject", "Delete Project", false, "fa fa-minus");
					myMenu.addNewChild("file", 2, "newFolder", "New Folder", false, "fa fa-folder-o");
					myMenu.addNewChild("file", 3, "rename", "Rename", false, "fa fa-pencil-square-o");
					myMenu.addNewChild("file", 4, "dupProject", "Duplicate Project", false, "fa fa-clone");
					myMenu.addNewChild("file", 5, "move", "Move to ...", false, "fa fa-minus");
					myMenu.addNewSeparator("move");
					myMenu.addNewChild("file", 7, "import", "Import", false, "fa fa-minus");
					myMenu.addNewChild("file", 8, "export", "Export", false, "fa fa-minus");
				myMenu.addNewSibling("file", "edit", "Edit", false);
					myMenu.addNewChild("edit", 0, "print", "Print", false, "fa fa-print");
					myMenu.addNewChild("edit", 1, "edit_undo", "Undo", false, "fa fa-undo");
					myMenu.addNewChild("edit", 2, "edit_redo", "Redo", false, "fa fa-repeat");
					myMenu.addNewSibling("edit_redo", "edit_split", "Edit",false);
						myMenu.addNewChild("edit_split", 0, "edit_cut", "Cut", false, "fa fa-scissors");
						myMenu.addNewChild("edit_split", 1, "edit_copy", "Copy", false, "fa fa-files-o");
						myMenu.addNewChild("edit_split", 2, "edit_paste", "Paste", false, "fa fa-clipboard");
						myMenu.addNewSeparator("edit_paste");
						myMenu.addNewChild("edit_split", 3, "edit_find", "Find and replace...", false, "fa fa-search");
				myMenu.addNewSibling("edit", "view", "View", false);
					myMenu.addNewChild("view", 0, "zoom_fit", "Zoom to fit", false, "fa fa-");
					myMenu.addNewChild("view", 1, "next_timescale", "Next timeScale", false, "fa fa-");
					myMenu.addNewChild("view", 2, "prev_timescale", "Previous timeScale", false, "fa fa-");
					myMenu.addNewChild("view", 3, "zoom_out", "Zoom Out", false, "fa icon-zoom-out");
					myMenu.addNewChild("view", 4, "zoom_in", "Zoom In", false, "fa icon-zoom-in");
					myMenu.addNewSibling("zoom_in", "section_levels", "Section levels",false);
						myMenu.addNewChild("section_levels", 0, "collapse_all", "Collapse all", false, "fa fa-");
						myMenu.addNewChild("section_levels", 1, "expand_all", "Expand all", false, "fa fa-");
						myMenu.addNewChild("section_levels", 2, "section_1", "1", false, "fa fa-");
						myMenu.addNewChild("section_levels", 3, "section_2", "2", false, "fa fa-");
						myMenu.addNewChild("section_levels", 4, "section_3", "3", false, "fa fa-");
						myMenu.addNewChild("section_levels", 5, "section_4", "4", false, "fa fa-");
						myMenu.addNewChild("section_levels", 6, "section_5", "5", false, "fa fa-");
						myMenu.addNewChild("section_levels", 7, "section_6", "6", false, "fa fa-");
						myMenu.addNewChild("section_levels", 8, "section_7", "7", false, "fa fa-");
						myMenu.addNewChild("section_levels", 9, "section_8", "8", false, "fa fa-");
						myMenu.addNewChild("section_levels", 10, "section_9", "9", false, "fa fa-");
					myMenu.addNewSibling("section_levels", "filter", "Filter",false);
						myMenu.addNewChild("filter", 0, "activeTasks", "Active tasks - Percentage Complete >0% & <100%", false, "fa fa-");
						myMenu.addNewChild("filter", 1, "completedTaks", "Completed tasks - Percentage Complete =100%", false, "fa fa-");
						myMenu.addNewChild("filter", 2, "criticalTasks", "Critical tasks", false, "");
						myMenu.addNewChild("filter", 3, "dataRange", "Date range - Percentage Complete >0 & <100", false, "");
						myMenu.addNewChild("filter", 4, "incompletedTasks", "Incomplete tasks - Between date range", false, "");
						myMenu.addNewChild("filter", 5, "lateTasks", "Late tasks - tasks not started before current date and tasks with 'Percentage Complete' converted to days and behind current date", false, "");
						myMenu.addNewChild("filter", 6, "milestones", "Milestones", false, "");
						myMenu.addNewChild("filter", 7, "taskRange", "Task Range", false, "");
						myMenu.addNewChild("filter", 8, "usingResources", "Using resources", false, "");
				myMenu.addNewSibling("view", "insert", "Insert", false);
				    myMenu.addNewChild("insert", 0, "newItem", "Add Item", false, "fa fa-plus");
					myMenu.addNewChild("insert", 1, "delItem", "Delete Item", false, "fa fa-minus");
					myMenu.addNewChild("insert", 2, "automatic", "Automatic", false, "fa fa-arrow-right");
					myMenu.addNewChild("insert", 3, "manual", "Manual", false, "");
					myMenu.addNewChild("insert", 4, "linkTask", "Link task", false, "fa fa-link");
					myMenu.addNewChild("insert", 5, "unlinkTask", "Unlink task", false, "fa fa-chain-broken");
					myMenu.addNewChild("insert", 6, "scrollToTask", "Scroll to task", false, "fa fa-arrow-right");
					myMenu.addNewChild("insert", 7, "taskInfo", "Task information", false, "fa fa-info-circle");
				myMenu.addNewSibling("insert", "format", "Format", false);
					myMenu.addNewChild("format", 0, "indent", "Indent", false, "fa fa-info-circle");
					myMenu.addNewChild("format", 1, "outdent", "Outdent", false, "fa fa-calendar");
					myMenu.addNewSibling("outdent", "subFormat", "Format", false);
						myMenu.addNewChild("subFormat", 0, "reset", "Reset", false, "fa fa-calendar");
						myMenu.addNewSeparator("reset");
						myMenu.addNewChild("subFormat", 2, "bold", "Bold", false, "fa fa-bold");
						myMenu.addNewChild("subFormat", 3, "italic", "Italic", false, "fa fa-italic");
						myMenu.addNewChild("subFormat", 4, "strike", "Strike through", false, "fa fa-strikethrough");
						myMenu.addNewChild("subFormat", 5, "underline", "Underline", false, "fa fa-underline");
						myMenu.addNewChild("subFormat", 6, "textColor", "Text Colour", false, "fa fa-th");
				myMenu.addNewSibling("format", "project", "Project", false);
					myMenu.addNewChild("project", 0, "projectInfo", "Project information", false, "fa fa-info-circle");
					myMenu.addNewChild("project", 1, "changeWorkingTime", "Change working time", false, "fa fa-calendar");
					myMenu.addNewChild("project", 2, "setBaseline", "Set baseline", false, "fa fa-opera");
					myMenu.addNewChild("project", 3, "importMsProject", "Import from MS Project", false, "fa fa-heart-o");
				myMenu.addNewSibling("project", "outputs", "Outputs", false);
					myMenu.addNewChild("outputs", 0, "senchaSearch", "Sencha Search", false, "fa fa-search");
					myMenu.addNewChild("outputs", 1, "exportPdf", "Export to pdf", false, "fa fa-file-pdf-o");
					myMenu.addNewChild("outputs", 2, "exportExcel", "Export to Excel", false, "fa fa-file-excel-o");
					myMenu.addNewChild("outputs", 3, "exportMsProject", "Export to MS Project", false, "fa fa-file-powerpoint-o");
			}
		};
	});
})();